### ISSUE TITLE
Importing unsupported Python packages

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#108]
Just wanted to document this.  In the `update-mlep` branch, when breaking out the py2 and py3 requirements, I removed some py3 packages that weren't being used by any of MY tests, but which were specifically added to support the Python EMS work.

There were no issues running vanilla OSM / E+ models (no Python EMS), and the error would only surface when importing into the Python packages into the EMS scripts that aren't installed. You need to look in the `sim.err` file:
```
Program Version,EnergyPlus, Version 9.4.0-998c4b761e, YMD=2021.01.13 23:26,
   ************* Successfully added path "/usr/local/lib/python3.6/dist-packages" to the sys.path in Python
   ************* Successfully added path "/usr/local/EnergyPlus-9-4-0" to the sys.path in Python
   ************* Successfully added path "/parse/bdd4875c-55f6-11eb-ad25-3af9d38d2919/workflow/Users/cmosiman/Github/alfalfa/tests/integration/models/refrig_case_osw/python" to the sys.path in Python
   ** Severe  ** Failed to import module "in"
   **   ~~~   ** Python error description follows:
   **   ~~~   ** ModuleNotFoundError("No module named 'symfit'",)
   **   ~~~   ** Python traceback follows:
   **   ~~~   ** ```
   **   ~~~   **  >>> Traceback (most recent call last):
   **   ~~~   **  >>>   File "./in.py", line 2, in <module>
    import case_models as cm
   **   ~~~   **  >>>   File "./case_models.py", line 2, in <module>
    from symfit import parameters, variables, log, Fit, Model
   **   ~~~   **  >>> ModuleNotFoundError: No module named 'symfit'
   **   ~~~   ** ```
   **  Fatal  ** Python import error causes program termination
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=Failed to import module "in"
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  1.27sec
```

At this point, Alfalfa just hangs in 'Starting' state, and from the mlep side there's no error saying 'EnergyPlus failed to run' or something of the sort, it just hangs waiting to receive data from bcvtb and eventually the socket times out:
```
Server started on 127.0.0.1:35211
Wrote socket.cfg
Launch EnergyPlus
Traceback (most recent call last):
  File "step_sim/step_osm.py", line 31, in <module>
    m.run()
  File "/usr/local/lib/python3.6/dist-packages/alfalfa_worker/step_sim/model_advancer.py", line 79, in run
    self.init_sim()
  File "/usr/local/lib/python3.6/dist-packages/alfalfa_worker/step_sim/osm_model_advancer.py", line 91, in init_sim
    [self.ep.status, self.ep.msg] = self.ep.accept_socket()
  File "/usr/local/lib/python3.6/dist-packages/mlep/mlep_process.py", line 162, in accept_socket
    (self.comm_socket, self.client_address) = self.server_socket.accept()
  File "/usr/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out
```

A few considerations:
- Do we want to have a better way of checking that EnergyPlus is running?
- Should we have some way of telling people that 'a python package they are trying to use is unsupported'?

**Comment by corymosiman12** [comment]
The specific bug was fixed here: https://github.com/NREL/alfalfa/commit/bd1e786463190e0d0e53f047ad82477f7fe57ce0

Anya - leaving open in case we want to add better error messages for these scenarios.

**Comment by anyaelena** [comment]
i added this debugging workflow to #110
