### ISSUE TITLE
Can't run Spawn model

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#273]
For the pre-release code, I have the below error immediately after kicking off "run" for an FMU that uses Spawn.  This was was working on main branch, so maybe this relates to the change to how we're running FMUs?  

w/in worker:
```
> which spawn
> /usr/local/bin/spawn
```

worker logs.  (nothing in simulate dir on worker looked useful)
```
Traceback (most recent call last):
  File "worker_fmu/step_fmu.py", line 332, in <module>
    runFMUSite.run()
  File "worker_fmu/step_fmu.py", line 167, in run
    self.step()
  File "worker_fmu/step_fmu.py", line 253, in step
    y_output = self.tc.advance(u)
  File "/alfalfa/alfalfa_worker/lib/testcase.py", line 151, in advance
    input=input_object)
  File "src/pyfmi/fmi.pyx", line 7573, in pyfmi.fmi.FMUModelME2.simulate
  File "src/pyfmi/fmi.pyx", line 301, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "src/pyfmi/fmi.pyx", line 295, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "/usr/local/JModelica/Python/pyfmi/fmi_algorithm_drivers.py", line 330, in __init__
    self.model.initialize()
  File "src/pyfmi/fmi.pyx", line 4475, in pyfmi.fmi.FMUModelBase2.initialize
  File "src/pyfmi/fmi.pyx", line 4469, in pyfmi.fmi.FMUModelBase2.initialize
  File "src/pyfmi/fmi.pyx", line 4417, in pyfmi.fmi.FMUModelBase2.enter_initialization_mode
```

**Comment by kbenne** [comment]
the long name of spawn (the one that includes the build she) needs to be in the path.

**Comment by anyaelena** [comment]
ok.  I'm running on Rancher and I'm wondering it it cached the develop images.  I'll try local instead

**Comment by anyaelena** [comment]
Yep, I see it warming up locally.  Sorry for the distraction!

**Comment by anyaelena** [comment]
Ok.  After warm up a real error that i think is related to the pyfmi changes:

```
Starting Simulation at 01/01/2017 for SPAWN-RUNPERIOD
Namespace(end_datetime='86400', site_id='c1a5dfb0-ac4f-11ec-953a-1172bf026387', start_datetime='0', step_sim_type='timescale', step_sim_value=5)
Traceback (most recent call last):
  File "alfalfa_worker/worker_fmu/step_fmu.py", line 335, in <module>
    runFMUSite.run()
  File "alfalfa_worker/worker_fmu/step_fmu.py", line 170, in run
    self.step()
  File "alfalfa_worker/worker_fmu/step_fmu.py", line 256, in step
    y_output = self.tc.advance(u)
  File "/alfalfa/alfalfa_worker/lib/testcase.py", line 152, in advance
    input=input_object)
  File "src/pyfmi/fmi.pyx", line 8125, in pyfmi.fmi.FMUModelME2.simulate
  File "src/pyfmi/fmi.pyx", line 378, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "src/pyfmi/fmi.pyx", line 374, in pyfmi.fmi.ModelBase._exec_simulate_algorithm
  File "/usr/local/lib/python3.6/dist-packages/PyFMI-2.9.5-py3.6-linux-x86_64.egg/pyfmi/fmi_algorithm_drivers.py", line 703, in solve
    self.simulator.simulate(self.final_time, self.ncp)
  File "assimulo/ode.pyx", line 180, in assimulo.ode.ODE.simulate
  File "assimulo/ode.pyx", line 300, in assimulo.ode.ODE.simulate
  File "assimulo/explicit_ode.pyx", line 101, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/explicit_ode.pyx", line 188, in assimulo.explicit_ode.Explicit_ODE._simulate
  File "assimulo/solvers/sundials.pyx", line 1935, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 1950, in assimulo.solvers.sundials.CVode.integrate
  File "assimulo/solvers/sundials.pyx", line 2194, in assimulo.solvers.sundials.CVode.initialize_options
assimulo.exception.AssimuloException: No support for SuperLU was detected, please verify that SuperLU and SUNDIALS has been installed correctly.
```

**Comment by kbenne** [comment]
I think this error is because the PyFMI install is not fully featured.

**Comment by kbenne** [comment]
@anyaelena oh and I see that you said the same thing I did. Yes totally the related to PyFMI. Yuck.

**Comment by anyaelena** [comment]
@kbenne @TShapinsky who can lead fixing it?

**Comment by TShapinsky** [comment]
What is the best way to reproduce this error?

**Comment by anyaelena** [comment]
For now, use the "wrapped.fmu" that i uploaded in chat (but don't check into repo).  Note that it has a pretty long warm up period before it starts to advance and throws the error.  Kyle's going to provide a smaller spawn fmu later today that will be more convenient for testing.

**Comment by TShapinsky** [comment]
@anyaelena I'm not getting the original error message you posted. did you have a resolution for this?

**Comment by TShapinsky** [comment]
oh, just realized i need to pull develop, building again

**Comment by kbenne** [comment]
Here is a good model to test with 

https://spawn.s3.amazonaws.com/models/Buildings_ThermalZones_EnergyPlus_Validation_ThermalZone_OneZoneOneYear.fmu

**Comment by kbenne** [comment]
I didn't consider that I gave you a vanilla spawn model, so it doesn't have all of the trimmings required by Alfalfa. (Since alfalfa uses testcase.py)

I see three options.

1. test with raw pyfmi 

2. we stop using testcase.py to run fmu

3. I give you a wrapped FMU


I assume you want option 3, however I'm a bit time constrained today and making a wrapped model is tedious, so it might be tomorrow before I have it.
