### ISSUE TITLE
If Uploaded OSW zip doesn't have a 'measures' directory worker fails to add site

### ISSUE THREAD

**Issue by TShapinsky** [NREL/alfalfa#282]
Like the title says. This is the error message:
```
alfalfa-worker-2  | Traceback (most recent call last):
alfalfa-worker-2  |   File "alfalfa_worker/worker_openstudio/add_site.py", line 239, in <module>
alfalfa-worker-2  |     adder.main()
alfalfa-worker-2  |   File "alfalfa_worker/worker_openstudio/add_site.py", line 91, in main
alfalfa-worker-2  |     self.add_osw()
alfalfa-worker-2  |   File "alfalfa_worker/worker_openstudio/add_site.py", line 176, in add_osw
alfalfa-worker-2  |     self.insert_os_tags(points_json_path, mapping_json_path)
alfalfa-worker-2  |   File "alfalfa_worker/worker_openstudio/add_site.py", line 115, in insert_os_tags
alfalfa-worker-2  |     with open(points_json_path, 'r') as f:
alfalfa-worker-2  | FileNotFoundError: [Errno 2] No such file or directory: '/parse/299ec11a-b063-11ec-b444-acde48001122/workflow/reports/haystack_report_haystack.json'
```
It appears that the measures directories don't get merged causing the haystack measure not to get run.

**Comment by TShapinsky** [comment]
Fixed by #401
