### ISSUE TITLE
AlfalfaException when uploading OS MediumOffice Prototype Model to cctwin server

### ISSUE THREAD

**Issue by tanushree04** [NREL/alfalfa#405]
To Reproduce: 

Upload model attached to alfalfa: https://cctwin.nrel.gov using the following simulation parameters

```
start_dt = datetime.datetime(2021, 7, 1, 0, 0, 0)
end_dt = datetime.datetime(2021, 7, 2, 0, 0, 0)
params = {
    "external_clock": False,
    "timescale": 5,
    "start_datetime": start_dt,
    "end_datetime": end_dt
}

```
The following error is seen: 	

```
AlfalfaException: Traceback (most recent call last):
  File "/alfalfa/alfalfa_worker/lib/job.py", line 104, in start
    [self.exec()](url)
  File "/alfalfa/alfalfa_worker/jobs/step_run_base.py", line 108, in exec
    self.advance_to_start_time()
  File "/alfalfa/alfalfa_worker/jobs/openstudio/step_run.py", line 100, in advance_to_start_time
    self.update_outputs_from_ep()
  File "/alfalfa/alfalfa_worker/jobs/openstudio/step_run.py", line 120, in update_outputs_from_ep
    _flag, _, outputs = mlep.mlep_decode_packet(packet)
  File "/usr/local/lib/python3.8/dist-packages/mlep/mlep_decode_packet.py", line 110, in mlep_decode_packet
    raise mlep.InputError('mlepDecodePacket', 'Invalid packet format: length is only %d.' % data_len)
mlep.mlep_error.InputError: ('mlepDecodePacket', 'Invalid packet format: length is only 0.')
```

Model attached here: 
[MediumOffice.zip](https://github.com/NREL/alfalfa/files/10667520/MediumOffice.zip)

**Comment by TShapinsky** [comment]
My best guess is that this is a result of 0.4.1 not providing adequate time for model warmup before attempting to communicate with it. This should be fixed in 0.5.0, but I'll need to confirm.

**Comment by TShapinsky** [comment]
Fixed!
