### ISSUE TITLE
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

### ISSUE THREAD

**Issue by abdulroqeeb** [NREL/alfalfa#61]
I am trying to setup Alfalfa following your Steps 1-5. However, when I run docker-compose up web, the build fails with error: ERROR: Service 'web' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

I am not so familiar with Node so it hard for me to troubleshoot this. I would appreciate any guidance on this. See full trace. 

`ERROR in ./app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
/root/node_modules/schema-utils/dist/util/hints.js:16
  const currentSchema = { ...schema
                          ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/schema-utils/dist/ValidationError.js:11:5)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/schema-utils/dist/validate.js:14:47)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/schema-utils/dist/index.js:3:18)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/babel-loader/lib/index.js:43:25)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
 @ multi ./app.js app[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 622 bytes {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module

npm ERR! Linux 4.19.76-linuxkit
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! web@0.0.1 build: `npm run clean && npm run build-server && webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the web@0.0.1 build script 'npm run clean && npm run build-server && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build-server && webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log`

**Comment by corymosiman12** [comment]
Hello @abdulroqeeb - which branch / commit are you trying to build from?

**Comment by abdulroqeeb** [comment]
> Hello @abdulroqeeb - which branch / commit are you trying to build from?

Hello @corymosiman12 , I tried to build from the default branch (develop).

**Comment by corymosiman12** [comment]
Ok...yeah, we need to change that (apologies).  Please build from the master branch and we will change the default branch to master.  Let us know if you have any other questions!  I will wait to close until I get confirmation from you that this is working as expected on your end.

**Comment by abdulroqeeb** [comment]
> Ok...yeah, we need to change that (apologies). Please build from the master branch and we will change the default branch to master. Let us know if you have any other questions! I will wait to close until I get confirmation from you that this is working as expected on your end.

I tried to build from the master branch but I got the same error. ERROR: Service 'web' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

**Comment by ariwoolar** [comment]
Hello, I am facing a similar issue as the one listed above on both Mac and Windows OS. " ERROR: Service 'web' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1." I would appreciate any assistance.

**Comment by corymosiman12** [comment]
Hey @ariwoolar can you confirm you are getting the same stack trace:
```
ERROR in ./app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
/root/node_modules/schema-utils/dist/util/hints.js:16
  const currentSchema = { ...schema
                          ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/schema-utils/dist/ValidationError.js:11:5)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/schema-utils/dist/validate.js:14:47)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/schema-utils/dist/index.js:3:18)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/root/node_modules/babel-loader/lib/index.js:43:25)
    at Module._compile (/root/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
 @ multi ./app.js app[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 622 bytes {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module

npm ERR! Linux 4.19.76-linuxkit
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! web@0.0.1 build: `npm run clean && npm run build-server && webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the web@0.0.1 build script 'npm run clean && npm run build-server && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build-server && webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by ariwoolar** [comment]
Yes, @corymosiman12 . it is the same stack trace

**Comment by corymosiman12** [comment]
kk I think I found the issues.  @ariwoolar @abdulroqeeb please try to build from this new branch: https://github.com/NREL/alfalfa/tree/issue/161

If I get a thumbs up from both of you, I will merges these into master.  Thanks for bringing the issues to our attention!

**Comment by ariwoolar** [comment]
Works great from my side, @corymosiman12 .  Thanks for your prompt assistance. I will keep in touch in case of any other issue.

**Comment by abdulroqeeb** [comment]
> kk I think I found the issues. @ariwoolar @abdulroqeeb please try to build from this new branch: https://github.com/NREL/alfalfa/tree/issue/161
> 
> If I get a thumbs up from both of you, I will merges these into master. Thanks for bringing the issues to our attention!

@corymosiman12 , build successfully completed. Thank you.
