### ISSUE TITLE
Integration tests hang instead of returning fail when add_site errors on worker.

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#78]
For example, the CI build hangs and eventually times out on test 
````
tests/integration/test_submit_file.py::TestSubmitFile::test_submit_osm
```` 

while the worker shows 

````
INFO:add_site:add_osm for uploads/de7da794-38d3-11eb-a2d3-88e9fe5dee0a/SmallOffice_Unitary_1.osm
Traceback (most recent call last):
  File "add_site/add_site.py", line 270, in <module>
    adder.main()
  File "add_site/add_site.py", line 63, in main
    self.add_osm()
  File "add_site/add_site.py", line 157, in add_osm
    self.os_files_final_touches_and_upload()
  File "add_site/add_site.py", line 104, in os_files_final_touches_and_upload
    make_ids_unique(self.upload_id, self.report_haystack_json, self.report_mapping_json)
TypeError: make_ids_unique() takes 2 positional arguments but 3 were given
````

**Comment by anyaelena** [comment]
I propose we fix this by adding configurable wait times in NREL/alfalfa-client#6 and updating tests to time out earlier.
